sandbox/apps/payments/payment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = (
	url(r'^$', views.index, name='index'),
	url(r'pay/$', views.pay, name="pay"),
	url(r'customer/$', views.payInfo, name="paymentInfo"),
	url(r'email/',views.subscribe, name='contact'),

)

sandbox/urls.py
import django
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from oscar.app import application
from oscar.views import handler403, handler404, handler500

from apps.gateway import urls as gateway_urls
from apps.payments.payment import urls as payment_urls
from apps.sitemaps import base_sitemaps

admin.autodiscover()

urlpatterns = [
    # Include admin as convenience. It's unsupported and only included
    # for developers.
    url(r'^admin/', admin.site.urls),

    # i18n URLS need to live outside of i18n_patterns scope of Oscar
    url(r'^i18n/', include(django.conf.urls.i18n)),

    # include a basic sitemap
    url(r'^sitemap\.xml$', views.index,
        {'sitemaps': base_sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', views.sitemap,
        {'sitemaps': base_sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

# Prefix Oscar URLs with language codes
urlpatterns += i18n_patterns(
    # Custom functionality to allow dashboard users to be created
    url(r'gateway/', include(gateway_urls)),
    #fork partner url
    url(r'payment/', include(payment_urls)),
    # Oscar's normal URLs
    url(r'^', application.urls),
)

if settings.DEBUG:
    import debug_toolbar

    # Server statics and uploaded media
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # Allow error pages to be tested
    urlpatterns += [
        url(r'^403$', handler403),
        url(r'^404$', handler404),
        url(r'^500$', handler500),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

sandbox/apps/payments/payment/models.py
from oscar.apps.payment.models import *  # noqa isort:skip
from django.db import models

class PaymentId(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    payment_id = models.CharField(max_length=1000)
    payment_request_id = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

sandbox/apps/payments/payment/forms.py
from django import forms
from .models import PaymentId

class PaymentForm(forms.Form):
    purpose = forms.CharField(label='purpose')
    amount = forms.IntegerField(label='amount')
    phone = forms.CharField(label='Your phone', max_length=10)
    email = forms.EmailField(label='Your email', max_length=100)
    name = forms.CharField(label='name', max_length=100)

class PaymentIdForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    payment_id = forms.CharField(max_length=1000)
    payment_request_id = forms.CharField(max_length=1000)

class SubscribeForm(forms.Form):
    email = forms.EmailField(max_length=100)

sandbox/apps/payments/payment/views.py
import requests
from .forms import PaymentForm, SubscribeForm
from .models import PaymentId
from django.shortcuts import render
from django.conf import settings
from django.core.mail import send_mail
import requests
import json
from django.http import HttpResponseRedirect, HttpResponse

def payInfo(request):
    info = PaymentId.objects.all()
    return render(request, 'payment/customerpay.html', {'info': info})

def index(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PaymentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # print form.cleaned_data['name']
            # print form.cleaned_data['purpose']
            # print form.cleaned_data['amount']
            # print form.cleaned_data['phone']
            # print form.cleaned_data['email']

            # instamojo
            headers = { "X-Api-Key": "test_eea66b45729f5d1e9d6fbf34083", "X-Auth-Token": "test_6e94dfdaa46c1eff191ab85419d"}
            payload = {
              'purpose': form.cleaned_data['purpose'],
              'amount': form.cleaned_data['amount'],
              'buyer_name': form.cleaned_data['name'],
              'email': form.cleaned_data['email'],
              'phone': form.cleaned_data['phone'],
              'redirect_url': 'http://159.65.155.242:8000/en-gb/payment/pay/',
              'send_email': False,
              'send_sms': False,
              'webhook': 'http://instamojo.dev/webhook/',
              'allow_repeated_payments': False,
            }
            data = requests.post("https://test.instamojo.com/api/1.1/payment-requests/", data=payload, headers=headers)
            item = data.json()
            return HttpResponseRedirect(item['payment_request']['longurl'])
            # end instamojo

    else:
        form = PaymentForm()


    template = 'payment/index.html',
    name = request.user
    email_id = request.user.email
    context={
    'name':name,
    'email_id':email_id,
    'form':form
    }
    return render(request, template, context)

def pay(request):
    a = request.GET["payment_id"]
    b = request.GET["payment_request_id"]
    c = request.user
    d = request.user.email
    p = PaymentId(name=c, email=d, payment_id=a, payment_request_id=b)
    p.save()
    # subject = 'thank you'
    # message = 'Welcome to hostmud'
    # from_email = settings.DEFAULT_FROM_EMAIL
    # to_list = ['keshav@hostmud.com']
    # send_mail(subject,message,from_email,to_list,fail_silently=True)
    # print('sent')
    context={
    'a':a,
    'b':b
    }
    return render(request, 'payment/pay.html', context)

def subscribe(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SubscribeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            mail = form.cleaned_data['email']
            subject = 'New Subscriber'
            message = 'You have new subcriber to your website. The Email id is %s' % mail
        # body = "you received a message from %s mobile number is %s and query is %s" % (from_email, number,  message)
            from_email = mail
            to_list = ['apsrajput008@gmail.com']
            send_mail(subject,message,from_email,to_list,fail_silently=True)
            # print('sent')
            # print(form.cleaned_data['email'])
            return HttpResponseRedirect('/')
            # end instamojo

    else:
        form = SubscribeForm()


    template = 'payment/email.html',
    context={
    'form':form
    }
    return render(request, template, context)

sandbox/templates/payment/customerpay.html
<!DOCTYPE html>
<html>
<head>
<style>

h1{
  font-size: 30px;
  color: #505050;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}


/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
}
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
</style>



</head>
<body>

  <section>
    <!--for demo wrap-->
    <h1>Check for the Payment of Customer</h1>
    <div class="tbl-header">
      <table cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Payment Id</th>
            <th>Payment Request Id</th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" border="0">
        <tbody>
          {% for info in info %}
          	<tr>
          		<td>{{info.name}}</td>
          		<td>{{info.email}}</td>
          		<td>{{info.payment_id}}</td>
          		<td>{{info.payment_request_id}}</td>
          	</tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  </section>




</body>
</html>

sandbox/templates/payment/email.html
<!DOCTYPE html>
<html>
<head>

<style>
body {
  margin: 0;
  background: #25A3FF;
  font-family: 'Roboto', sans-serif;
}

h1 {
  position: relative;
  color: #fff;
  opacity: 0;
  transition: .8s ease-in-out;
}

#progress {
  position: absolute;
  background: #0069ec;
  height: 100vh;
  width: 0;
  transition: width 0.2s ease-in-out;
}

.center {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}

/******
  Form
 ******/

#register {
  background: #fff;
  position: relative;
  width: 410px;
  padding: 2px 15px 20px 15px;
  box-shadow: 0 16px 24px 2px rgba(0,0,0,0.14), 0 6px 30px 5px rgba(0,0,0,0.12), 0 8px 10px -5px rgba(0,0,0,0.3);
  transition: transform .1s ease-in-out;
}

#register.close {
  width: 0;
  padding: 0;
  overflow: hidden;
  transition: .8s ease-in-out;
  box-shadow: 0 16px 24px 2px rgba(0,0,0,0);
}

.next {
  position: absolute;
  right: 20px;
  bottom: 10px;
  font-size: 40px;
  color: #25a3ff;
  float: right;
  cursor: pointer;
}
.next:hover {color: #333}
.wrong .next {color: #ff2d26}
.close .next {color: #fff}

#inputContainer {
  position: relative;
  opacity: 0;
  width: 350px;
  margin-top: 25px;
  transition: opacity .3s ease-in-out;
}

#inputContainer input {
  width: 100%;
  padding: 0 5px;
  border: none;
  font-size: 20px;
  font-weight: bold;
  outline: 0;
  background: transparent;
  box-shadow:none;
}

#inputLabel {
  position: absolute;
  pointer-events: none;
  top: 0;
  left: 0;
  font-size: 20px;
  font-weight: bold;
  padding: 0 5px;
  transition: .2s ease-in-out;
}

#inputContainer input:valid + #inputLabel {
  top: -15px;
  font-size: 11px;
  font-weight: normal;
  color: #9e9e9e;
}

#inputProgress {
  position: absolute;
  border-bottom: 2px solid #25a3ff;
  padding: 3px 0;
  width: 0;
  transition: width .6s ease-in-out;
}

.wrong #inputProgress {
  border-color: #ff2d26;
}
</style>
</head>
<body>
  <div id="progress"></div>

  <div class="center">
    <div id="register">

      <i id="progressButton" class="ion-android-arrow-forward next"></i>

    <form method="post" action="">
      {% csrf_token %}
      <div id="inputContainer">
    <input type="email" name="email" required="" autofocus id="inputField" maxlength="100">
        <label id="inputLabel"></label>
        <div id="inputProgress"></div>
      </div>
    </form>

    </div>
  </div>
<!--
<form method="post" action="">
{% csrf_token %}
  <label for="id_email">Email:</label><input type="email" name="email" required="" id="id_email" maxlength="100">
  </form> -->
  <!-- <form method='post' action="">

{% csrf_token %}

{{form}}
</form> -->

</body>
<script>
var questions = [
  {question:"Please Enter Your Email?"},
]

/**********

  !!!!!
  New Version: https://codepen.io/arcs/pen/rYXrNQ
  !!!!!

  Credits for the design go to XavierCoulombeM
  https://dribbble.com/shots/2510592-Simple-register-form

  This Pen uses no libraries except fonts and should
  work on all modern browsers

  The answers are stored in the `questions` array
  with the key `value`.

 **********/

;(function(){

  var tTime = 100  // transition transform time from #register in ms
  var wTime = 200  // transition width time from #register in ms
  var eTime = 1000 // transition width time from inputLabel in ms

  // init
  // --------------
  var position = 0

  putQuestion()

  progressButton.addEventListener('click', validate)
  inputField.addEventListener('keyup', function(e){
    transform(0, 0) // ie hack to redraw
    if(e.keyCode == 13) validate()
  })

  // functions
  // --------------

  // load the next question
  function putQuestion() {
    inputLabel.innerHTML = questions[position].question
    inputField.value = ''
    inputField.type = questions[position].type || 'text'
    inputField.focus()
    showCurrent()
  }

  // when all the questions have been answered
  function done() {

    // remove the box if there is no next question
    register.className = 'close'

    // add the h1 at the end with the welcome text
    var h1 = document.createElement('h1')
    h1.appendChild(document.createTextNode('Thank you, Redirecting to main page!'))
    setTimeout(function() {
      register.parentElement.appendChild(h1)
      setTimeout(function() {h1.style.opacity = 1}, 50)
    }, eTime)

  }

  // when submitting the current question
  function validate() {

    // set the value of the field into the array
    questions[position].value = inputField.value

    // check if the pattern matches
    if (!inputField.value.match(questions[position].pattern || /.+/)) wrong()
    else ok(function() {

      // set the progress of the background
      progress.style.width = ++position * 100 / questions.length + 'vw'

      // if there is a new question, hide current and load next
      if (questions[position]) hideCurrent(putQuestion)
      else hideCurrent(done)

    })

  }

  // helper
  // --------------

  function hideCurrent(callback) {
    inputContainer.style.opacity = 0
    inputProgress.style.transition = 'none'
    inputProgress.style.width = 0
    setTimeout(callback, wTime)
  }

  function showCurrent(callback) {
    inputContainer.style.opacity = 1
    inputProgress.style.transition = ''
    inputProgress.style.width = '100%'
    setTimeout(callback, wTime)
  }

  function transform(x, y) {
    register.style.transform = 'translate(' + x + 'px ,  ' + y + 'px)'
  }

  function ok(callback) {
    register.className = ''
    setTimeout(transform, tTime * 0, 0, 10)
    setTimeout(transform, tTime * 1, 0, 0)
    setTimeout(callback,  tTime * 2)
  }

  function wrong(callback) {
    register.className = 'wrong'
    for(var i = 0; i < 6; i++) // shaking motion
      setTimeout(transform, tTime * i, (i%2*2-1)*20, 0)
    setTimeout(transform, tTime * 6, 0, 0)
    setTimeout(callback,  tTime * 7)
  }

}())
</script>
</html>

sandbox/templates/payment/index.html
<!DOCTYPE html>
<html>
<head>
  <title>test</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">


</head>
<body>
  <style>

  body
  {
  	background-color:#e2e2e2a8;
    margin:0;
  }

  body,input
  {
  	font-family:Nunito;
  }

  input
  {
  	border-width:0px;
  	outline:none;
  	font-weight:bold;
  }

  .b3
  {
  	border-radius: 3px;
  	-webkit-border-radius: 3px;
  	-moz-border-radius: 3px;
  	-o-border-radius: 3px;
  	-ms-border-radius: 3px;
  }

  .tb
  {
  	display:table;
  	width:100%;
  }

  .td
  {
  	display:table-cell;
  	vertical-align:middle;
  }

  .material-icons
  {
  	color:#bbb;
  	vertical-align:middle;
  }

  .icn
  {
  	width:24px;
  	padding:10px;
  }

  .mrg3b
  {
  	margin-bottom:30px;
  }

  .mrg25t
  {
  	margin-top:25px;
  }

  #frm-cvr
  {
    background:#212554;
  	font-size:16px;
  	width:340px;
  	margin:0 auto;
  	padding:40px;
  	font-weight:bold;
    margin-top: 4em;
  }

  .cl-wh
  {
  	color:#fff;
  }

  #f-mlb
  {
  	text-align:center;
  	font-size: 26px;
  	margin-bottom:25px;
  }

  .f-i-bx
  {
    margin-top: 7px;
    background-color: #fff;
  	overflow:hidden;
  }

  .f-i-bx input
  {
  	width:100%;
  	height:24px;
  	font-size: 13.333333px;
      font-family: nunito;
  	color:#4e4e4e;
  	background-color:transparent;
  	padding:0px;
  }

  .prt
  {
  	padding-right:10px;
  }

  form label
  {
  	padding-left:3px;
  }

  #tc-bx
  {
      margin-top: 25px;
      text-align: center;
      color: #c4cfd4;
      font-size: 14px;
      font-weight: normal;
  }

  #tc-bx a
  {
  	 color:#f1f5f1;
  	 text-decoration:none;
  }

  .f-i-bx,#s-btn input
  {
  	box-shadow: 0px 4px 4px #303f94;
  	-webkit-box-shadow: 0px 4px 4px #303f94;
  	-moz-box-shadow: 0px 4px 4px #303f94;
  	-o-box-shadow: 0px 4px 4px #303f94;
  	-ms-box-shadow: 0px 4px 4px #303f94;
  }

  #s-btn input
  {
      padding: 10px;
      width: 100%;
  	  color: #fff;
  	  font-size: 20px;
      cursor: pointer;
  	  background: linear-gradient(#536ae8, #3e50b3);
  	background: -webkit-linear-gradient(#536ae8, #3e50b3);
  	background: -moz-linear-gradient(#536ae8, #3e50b3);
  	background: -o-linear-gradient(#536ae8, #3e50b3);
  	background: -ms-linear-gradient(#536ae8, #3e50b3);
  }

  #s-btn input:active
  {
  	position:relative;
  	top:3px;
  	box-shadow: 0px 2px 2px #202c6d;
  	-webkit-box-shadow: 0px 2px 2px #202c6d;
  	-moz-box-shadow: 0px 2px 2px #202c6d;
  	-o-box-shadow: 0px 2px 2px #202c6d;
  	-ms-box-shadow: 0px 2px 2px #202c6d;
  }
.disable{
  display:none;
}
</style>

{% load history_tags %}
{% load basket_tags %}
{% load currency_filters %}
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

<!-- <div class="mini-cart-sub">
                      {% if request.basket.num_lines %}

											<div class="cart-totals">
                        {% if request.basket.is_tax_known %}
												<h5>{% trans "Total:" %}  <span>{{ request.basket.total_incl_tax|currency:request.basket.currency }}</span></h5>
                        {% else %}
												<h5>{% trans "Total:" %} <span>{{ request.basket.total_excl_tax|currency:request.basket.currency }}</span></h5>
                        {% endif %}
											</div>
                      {% endif %}
										</div> -->


<div id="frm-cvr">
			<div class="cl-wh" id="f-mlb">Please Provide Information</div>
			<form action="{% url "index" %}" method="post">
        {% csrf_token %}

				<label class="cl-wh f-lb" for="id_purpose">Purpose : Payment for Book</label>
        <div  class="disable">
				<label class="cl-wh f-lb" for="id_purpose">Purpose</label>
				<div class="f-i-bx b3 mrg3b">
					<div class="tb">
						<div class="td icn"><i class="material-icons">Book</i></div>
						<div class="td prt"><input type="text" name="purpose" required="" value="book payment" id="id_purpose"></div>
					</div>
				</div>
      </div>
<br><br>
      <label class="cl-wh f-lb">Amount : {{ request.basket.total_incl_tax|currency:request.basket.currency }}</label>
      <div  class="disable">
				<label class="cl-wh f-lb"  for="id_amount">Amount</label>
				<div class="f-i-bx b3 mrg3b">
					<div class="tb">
						<div class="td icn"><i class="material-icons">&#8377;</i></div>
						<div class="td prt"><input type="number" name="amount" value="{{ request.basket.total_incl_tax }}" required="" id="id_amount"></div>
					</div>
				</div>
      </div>

<br><br>
<label class="cl-wh f-lb" for="id_name">Name</label>
<div class="f-i-bx b3 mrg3b">
  <div class="tb">
    <div class="td icn"><i class="material-icons"><i class="fas fa-user"></i></i></div>
    <div class="td prt"><input type="text" name="name" required="" value="{{name}}" id="id_name" maxlength="100"></div>
  </div>
</div>
				<label class="cl-wh f-lb" for="id_phone">Phone</label>
				<div class="f-i-bx b3 mrg3b">
					<div class="tb">
						<div class="td icn"><i class="material-icons">+91</i></div>
						<div class="td prt"><input type="text" name="phone" required="" id="id_phone" maxlength="10"></div>
					</div>
				</div>
				<label class="cl-wh f-lb" for="id_email">Email</label>
				<div class="f-i-bx b3 mrg3b">
					<div class="tb">
						<div class="td icn"><i class="material-icons"><i class="fas fa-envelope"></i></i></div>
						<div class="td prt"><input type="email" name="email" value="{{email_id}}" required="" id="id_email" maxlength="100"></div>
					</div>
				</div>

				<div id="s-btn" class="mrg25t"><input type="submit" value="Submit" class="b3"></div>
			</form>
		</div>
    <!-- {% csrf_token %}
    <label for="id_purpose">purpose:</label><input type="text" name="purpose" placeholder="for book" required=""  value="book payment" id="id_purpose">
<label for="id_amount">amount:</label><input type="number" name="amount" required="" id="id_amount">
<label for="id_phone">Your phone:</label><input type="text" name="phone" required="" id="id_phone" maxlength="10">
<label for="id_email">Your email:</label><input type="email" name="email" value="{{email_id}}" required="" id="id_email" maxlength="100">
<label for="id_name">name:</label><input type="text" name="name" required="" value="{{name}}" id="id_name" maxlength="100">

<button type="submit" id="submit">Sign up</button>
</form> -->
</body>

</html>

sandbox/templates/payment/pay.html
<!DOCTYPE html>
{% load i18n %}
<html>
<head>
  <title>test</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
    jQuery(function(){
       jQuery('#modal').click();
    });
    </script>
<style>
body{
  margin:0;
  background:#7bb2c3 !important;
}
.btn12{
  padding:10px 0;
}
li{
  color:#504d4d;
  font-size:22px;
  font-weight: 700;
}
label{
  margin-top: 10px;
}
h2{
  padding:11px 5px;
  color:#6d717d;
  font-weight: 700;
  font-size: 27px;
  margin-left: -30px;
  width: fit-content;
}
</style>
</head>
<body>
<!-- <div class="col-sm-12 col-xs-4 col-md-8 col-lg-8" style="margin-top:1.5em;">
<img src="http://www.aaditritechnology.com/images/mobile_payment.gif" />
</div> -->

<div class="col-sm-12 col-xs-4 col-md-4 col-lg-4" style="margin-top:1.5em;display:none;">
  <div class="btn12">
    <!-- <ul style="color:#fff;list-style:none;margin-left:-15px;">
      <h2>Your Payment Information</h2>
      <label>PAYMENT_ID</label><li>{{a}}</li>
      <label>PAYMENT_REQUEST_ID</label><li style="margin-bottom:50px;">{{b}}</li>
      <a href="{% url 'checkout:preview' %}" style="background:#272727;padding:14px 50px;border-radius:10px;cursor:pointer;font-weight;color:#fff;font-size:23px;">Return</a>
    </ul> -->
    {% block place_order %}
        <form method="post" action="{% url 'checkout:preview' %}" id="place_order_form">
            {% csrf_token %}
            <input type="hidden" name="action" value="place_order" />


            <div style="display:none">
                {% block hiddenforms %}{% endblock %}
            </div>

                    <div class="order-button-payment ">
                         <button id='modal' type="submit" class="btn btn-primary btn-lg btn-block" data-loading-text="{% trans 'Submitting...' %}" style="background:#3c74b9;border:#fff;">{% trans "COD" %}</button>
                    </div>

        </form>
    {% endblock place_order %}
  </div>
</div>
</body>

</html>